spring:
  application:
    name: api-auth-system
  security:
    user:
      name: admin      # ??? ???
      password: password


  # H2 Database (???)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

# JWT ??
jwt:
  secret: mySuperSecretKeyForJWTGenerationChangeThisInProduction
  access-expiration: 600000 #3600000        # 1시간 (밀리초)
  refresh-expiration: 2592000000    # 30일 (밀리초)

# ??
logging:
  level:
    com.example.api-auth-system: DEBUG
    org.springframework.security: DEBUG
